---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-processor
  labels:
    app: payment-processor
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: payment-processor
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: payment-processor
    spec:
      containers:
      - name: payment-processor
        image: localhost:6000/payment-processor:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        envFrom:
        - configMapRef:
            name: payment-processor-env
      terminationGracePeriodSeconds: 180