resources:
- deployment.yaml
- service.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: redis-env
  literals:
    - REDIS_PASSWORD=uRyvdi7kLVv7TUZ2Fv3EX4
    - OTEL_EXPORTER_OTLP_ENDPOINT=http://aspire-dashboard:18889
    - OTEL_SERVICE_NAME=redis

