name: Trigger auto deployment for eshop-dev

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/eshop-dev-AutoDeployTrigger-4194207a-49cf-4648-a5e8-16882b21e994.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ESHOPDEV_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.ESHOPDEV_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ESHOPDEV_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: 
          registryUsername: ${{ secrets.ESHOPDEV_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ESHOPDEV_REGISTRY_PASSWORD }}
          containerAppName: eshop-dev
          resourceGroup: RG1
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


