name: eShop Pull Request Validation

on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'


jobs:  
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'
      - name: Install Workloads
        run: dotnet workload install aspire
      - name: Build 
        run: dotnet build eShop.Web.slnf
      - name: Test
        run: dotnet test eShop.Web.slnf